name: Check Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs every Monday at 00:00 UTC to catch "link rot"
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Check all markdown files in the repo
          args: --verbose --no-progress "**/*.md"
          # Fail the build if broken links are found
          fail: true

      - name: Create Issue From Broken Links
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "🔗 Broken Links Detected"
          content-filepath: ./lychee/out.md
          labels: report, automated-issue